[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NETLIFY_NEXT_VERIFY_FORMS = "false"

# Usuwam plugin @netlify/plugin-nextjs, ponieważ powoduje błędy budowania
# [[plugins]]
#  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/(.*).(jpg|jpeg|png|svg|webp|avif|ico)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 